version: '3.1'
services:
  db:
    image: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    env_file:
      - var.env
  web:
    build: ./sources
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - var.env
    volumes:
      - ./sources:/code
    ports:
      - "8000:8000"
    depends_on:
      - db