# Generated by Django 2.1.7 on 2019-02-25 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Catégorie')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('description', models.TextField()),
                ('count', models.IntegerField(verbose_name='Quantité')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix')),
                ('caution', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Caution')),
                ('image', models.ImageField(upload_to='', verbose_name='Image')),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Stocks.Categorie', verbose_name='Catégorie')),
            ],
        ),
    ]
