# Generated by Django 2.1.7 on 2019-02-25 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='element',
            name='caution',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Caution'),
        ),
        migrations.AlterField(
            model_name='element',
            name='count',
            field=models.IntegerField(default=1, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='element',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='element',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix'),
        ),
    ]
