# Generated by Django 2.1.7 on 2019-02-25 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stocks', '0004_auto_20190225_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='element',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
