# Generated by Django 2.1.7 on 2019-02-25 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stocks', '0005_auto_20190225_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
        migrations.AddField(
            model_name='element',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
