# Generated by Django 2.1.7 on 2019-02-25 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stocks', '0007_auto_20190225_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='marque',
            name='slug',
            field=models.SlugField(blank=True, default='', editable=False, unique=True),
        ),
    ]
